### ISSUE TITLE
Instrument Name in MethodModifications

### ISSUE THREAD

**Issue by mammmals** [CMRose3355/TomahaqCompanion#1]
Do we need a form entry/textbox for allowing the user to change the Instrument name? Will this create any issues for Lumos methods?

TomahacCompanionForm.cs, Line 783:
`MethodModifications methodMods = new MethodModifications("1", "OrbitrapFusion", "Calcium", "SL");`

**Comment by CMRose3355** [comment]
That should work for both Lumos and Fusion. I will look into the other
email soon. I am out of the office right now. I might have time to look at
it tonight or tomorrow morning.

**Comment by mammmals** [comment]
No rush, and I just saw you emailed me. I'll take a look at the RT/mass range difference.
